title: "Md Tanvir Islam Emon"
author: "Md Tanvir Islam Emon"
email: "your.email@example.com"
description: "Material Science & Engineering student | Cybersecurity & Penetration Testing Enthusiast"
url: "https://your-username.github.io"     # no trailing slash
baseurl: "/tanvir-portfolio"               # leading slash for project repo
remote_theme: "mmistakes/minimal-mistakes" # use remote theme
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
